from src.core.database import db


class JyA(db.Model):
    __tablename__ = "jya"
    __table_args__ = {"extend_existing": True}
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    lastname = db.Column(db.String(20), nullable=False)
    document_number = db.Column(db.String(255), unique=True, nullable=False)
    age = db.Column(db.Integer, nullable=False)
    birthdate = db.Column(db.Date, nullable=False)
    place_of_birth = db.Column(db.String(50), nullable=False)
    current_address = db.Column(db.String(50), nullable=False)
    phone_number = db.Column(db.String(50), nullable=False)
    emergy_contact = db.Column(db.String(255), nullable=False)
    phone_number_emergy = db.Column(db.String(20), nullable=False)
    is_scholarship_holder = db.Column(db.Boolean, nullable=False)
    observations = db.Column(db.String(255), nullable=True)
    has_a_disability_certificate = db.Column(db.Boolean, nullable=False)
    with_what_diagnosis = db.Column(db.String(255), nullable=True)
    other = db.Column(db.String(255), nullable=True)
    disability_type = db.Column(db.String(255), nullable=False)
    has_allowance = db.Column(db.Boolean, nullable=False)
    allowance_type = db.Column(db.String(255), nullable=True)
    has_a_pension = db.Column(db.Boolean, nullable=False)
    pension_type = db.Column(db.String(255), nullable=True)
    social_work = db.Column(db.String(255), nullable=True)
    affiliation_number = db.Column(db.String(255), nullable=True)
    has_conservatorship = db.Column(db.Boolean, nullable=False)
    social_work_observation = db.Column(db.String(255), nullable=True)
    professionals = db.Column(db.String(255), nullable=True)
    fk_institution_id = db.Column(
        db.Integer, db.ForeignKey("institutions.id"), nullable=False)
    current_year_institution = db.Column(db.String(10), nullable=False)
    institution_observations = db.Column(db.String(50), nullable=True)
    institutional_work_proposal = db.Column(db.String(30), nullable=False)
    condition = db.Column(db.String(8), nullable=False)
    headquarters = db.Column(db.String(5), nullable=False)
    days = db.Column(db.JSON, nullable=False)
    teacher_or_therapist = db.Column(db.Integer, db.ForeignKey("members.id"))
    horse_driver = db.Column(db.Integer, db.ForeignKey("members.id"))
    horse = db.Column(db.Integer, db.ForeignKey("ecuestre.id"))
    runway_assistant = db.Column(db.Integer, db.ForeignKey("members.id"))
    is_erased = db.Column(db.Boolean, default=False)
    is_debtor = db.Column(db.Boolean, default=False)
